spring:
  application:
    name: eureka-server
server:
  port: 8761
  ssl:
    enabled: true
    key-alias: eureka-server
    key-store-type: PKCS12
    #key-store: classpath:eureka-server.p12
    key-store: /home/sengp/git/java-tutorials/spring/micro-services/certs/eureka-server.p12
    key-store-password: changeit
    trust-store: /home/sengp/git/java-tutorials/spring/micro-services/certs/mycerts
    trust-store-password: changeit
    trust-store-type: JKS
    #client-auth: need
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/

logging:
  file: ${logging.baseloc:/tmp/eureka-server}/${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}.log