version: '3'
services:
  db-service:
    restart: always
    image: pratik006/db-service:0.0.1-SNAPSHOT
    container_name: db-service
    environment:
      - EUREKA_URI=http://eureka-server:8080/eureka
      - MYSQL_DB_HOST=mysql
      - MYSQL_DB_PORT=3306
      - MYSQL_DATABASE=test
    expose:
      - "8080"
    ports:
      - 8081:8080
#    depends_on:
#      - mysql
#      - eureka-server