spring:
  application:
    name: student-service
server:
  port: 8080

services:
  core-api:
    host: ${CORE_API_HOST}
logging:
  #file: ${logging.baseloc}/${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.netflix.hystrix: DEBUG
