spring:
  application:
    name: student-service
  eureka:
    #client:
      #serviceUrl:
        #defaultZone: http://localhost:8761/eureka
    instance:
      #preferIpAddress: true
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 9083