###
#   Database Settings
###
spring:
  application:
    name: db-service
  datasource:
    # H2 configuration
#    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

    url: jdbc:mysql://localhost:3306/test
    platform: mysql
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        #use_sql_comments: true
        #format_sql: true
eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/

server:
  #port: 9091
  ssl:
    #enabled: true
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
    #key-store: classpath:${spring.application.name}.p12
    key-store: /home/sengp/git/java-tutorials/spring/micro-services/certs/db-service.p12
    key-store-password: changeit
    trust-store: /home/sengp/git/java-tutorials/spring/micro-services/certs/mycerts
    trust-store-password: changeit
    trust-store-type: JKS

port:
  number:
    min: 9091
    max: 9099

logging:
  file: ${logging.baseloc:/tmp/tests}/${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}.log