###
#   Database Settings
###
spring:
  datasource:
    # H2 configuration
#    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

    url: jdbc:mysql://localhost:3306/test
    platform: mysql
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        #use_sql_comments: true
        #format_sql: true

  ###
  #   H2 Settings
  ###
#  h2:
#    console:
#      enabled: true
#      path: /console
#      settings:
#        trace: false
#        web-allow-others: false




  application:
    name: db-service
  eureka:
#    client:
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      #preferIpAddress: true
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 9091
  ssl:
    key-alias: db-service
    key-store-type: JKS
    key-password: password
    key-store: classpath:db-service.jks

port:
  number:
    min: 9081
    max: 9089

logging:
  file: ${logging.baseloc?logging.baseloc:/tmp/tests}/${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}.log